drop DATABASE db_shig cascade if exists;
CREATE TS DATABASE db_shig;
CREATE TABLE db_shig.t_electmeter (
  k_timestamp timestamp NOT NULL,
  elect_name varchar(63) NOT NULL,
  vol_a double NOT NULL,
  cur_a double NOT NULL,
  powerf_a double,
  allenergy_a int NOT NULL,
  pallenergy_a int NOT NULL,
  rallenergy_a int NOT NULL,
  allrenergy1_a int NOT NULL,
  allrenergy2_a int NOT NULL,
  powera_a double NOT NULL,
  powerr_a double NOT NULL,
  powerl_a double NOT NULL,
  vol_b double NOT NULL,
  cur_b double NOT NULL,
  powerf_b double NOT NULL,
  allenergy_b int NOT NULL,
  pallenergy_b int NOT NULL,
  rallenergy_b int NOT NULL,
  allrenergy1_b int NOT NULL,
  allrenergy2_b int NOT NULL,
  powera_b double NOT NULL,
  powerr_b double NOT NULL,
  powerl_b double NOT NULL,
  vol_c double NOT NULL,
  cur_c double NOT NULL,
  powerf_c double NOT NULL,
  allenergy_c int NOT NULL,
  pallenergy_c int NOT NULL,
  rallenergy_c int NOT NULL,
  allrenergy1_c int NOT NULL,
  allrenergy2_c int NOT NULL,
  powera_c double NOT NULL,
  powerr_c double NOT NULL,
  powerl_c double NOT NULL,
  vol_ab double,
  vol_bc double,
  vol_ca double,
  infre double NOT NULL,
  powerf double NOT NULL,
  allpower double NOT NULL,
  pallpower double NOT NULL,
  rallpower double NOT NULL,
  powerr double NOT NULL,
  powerl double NOT NULL,
  allrenergy1 double NOT NULL,
  allrenergy2 double NOT NULL
) ATTRIBUTES (machine_code varchar(64) NOT NULL, op_group varchar(64) NOT NULL, location varchar(64) NOT NULL, cnc_number int) PRIMARY TAGS(machine_code);

SELECT machine_code, max(cur_a) as max_cur,min(cur_a) as min_cur,avg(cur_a) as avg_cur, sum(cur_a) as sum_cur, count(cur_a) as count_cur FROM db_shig.t_electmeter group by machine_code;

use defaultdb;
drop DATABASE db_shig cascade;