CREATE TS DATABASE db_shig;

CREATE TABLE db_shig.t_electmeter (
  k_timestamp timestamp NOT NULL,
  elect_name varchar(63) NOT NULL,
  vol_a double NOT NULL,
  cur_a double NOT NULL,
  powerf_a double,
  allenergy_a int NOT NULL,
  pallenergy_a int NOT NULL,
  rallenergy_a int NOT NULL,
  allrenergy1_a int NOT NULL,
  allrenergy2_a int NOT NULL,
  powera_a double NOT NULL,
  powerr_a double NOT NULL,
  powerl_a double NOT NULL,
  vol_b double NOT NULL,
  cur_b double NOT NULL,
  powerf_b double NOT NULL,
  allenergy_b int NOT NULL,
  pallenergy_b int NOT NULL,
  rallenergy_b int NOT NULL,
  allrenergy1_b int NOT NULL,
  allrenergy2_b int NOT NULL,
  powera_b double NOT NULL,
  powerr_b double NOT NULL,
  powerl_b double NOT NULL,
  vol_c double NOT NULL,
  cur_c double NOT NULL,
  powerf_c double NOT NULL,
  allenergy_c int NOT NULL,
  pallenergy_c int NOT NULL,
  rallenergy_c int NOT NULL,
  allrenergy1_c int NOT NULL,
  allrenergy2_c int NOT NULL,
  powera_c double NOT NULL,
  powerr_c double NOT NULL,
  powerl_c double NOT NULL,
  vol_ab double,
  vol_bc double,
  vol_ca double,
  infre double NOT NULL,
  powerf double NOT NULL,
  allpower double NOT NULL,
  pallpower double NOT NULL,
  rallpower double NOT NULL,
  powerr double NOT NULL,
  powerl double NOT NULL,
  allrenergy1 double NOT NULL,
  allrenergy2 double NOT NULL
) ATTRIBUTES (machine_code varchar(64) NOT NULL, op_group varchar(64) NOT NULL, location varchar(64) NOT NULL, cnc_number int) PRIMARY TAGS(machine_code);


CREATE TABLE db_shig.t_cnc (
  k_timestamp timestamp NOT NULL,
  cnc_sn varchar(200),
  cnc_sw_mver varchar(30),
  cnc_sw_sver varchar(30),
  cnc_tol_mem varchar(10),
  cnc_use_mem varchar(10),
  cnc_unuse_mem varchar(10),
  cnc_status varchar(2),
  path_quantity varchar(30),
  axis_quantity varchar(30),
  axis_path varchar(100),
  axis_type varchar(100),
  axis_unit varchar(100),
  axis_num varchar(100),
  axis_name varchar(100),
  sp_name varchar(100),
  abs_pos varchar(200),
  rel_pos varchar(200),
  mach_pos varchar(200),
  dist_pos varchar(200),
  sp_override double,
  sp_set_speed varchar(30),
  sp_act_speed varchar(30),
  sp_load varchar(300),
  feed_set_speed varchar(30),
  feed_act_speed varchar(30),
  feed_override varchar(30),
  servo_load varchar(300),
  parts_count varchar(30),
  cnc_cycletime varchar(30),
  cnc_alivetime varchar(30),
  cnc_cuttime varchar(30),
  cnc_runtime varchar(30),
  mprog_name varchar(500),
  mprog_num varchar(30),
  sprog_name varchar(500),
  sprog_num varchar(30),
  prog_seq_num varchar(30),
  prog_seq_content varchar(1000),
  alarm_count varchar(10),
  alarm_type varchar(100),
  alarm_code varchar(100),
  alarm_content varchar(2000),
  alarm_time varchar(200),
  cur_tool_num varchar(20),
  cur_tool_len_num varchar(20),
  cur_tool_len varchar(20),
  cur_tool_len_val varchar(20),
  cur_tool_x_len varchar(20),
  cur_tool_x_len_val varchar(20),
  cur_tool_y_len varchar(20),
  cur_tool_y_len_val varchar(20),
  cur_tool_z_len varchar(20),
  cur_tool_z_len_val varchar(20),
  cur_tool_rad_num varchar(20),
  cur_tool_rad varchar(20),
  cur_tool_rad_val varchar(20),
  device_state INT,
  value1 varchar(10),
  value2 varchar(10),
  value3 varchar(10),
  value4 varchar(10),
  value5 varchar(10)) ATTRIBUTES (machine_code varchar(64) NOT NULL, op_group varchar(64) NOT NULL, brand varchar(64) NOT NULL, number_of_molds int) PRIMARY TAGS(machine_code, op_group);
  
  explain SELECT last_row(*) FROM db_shig.t_electmeter where 1=1 group by machine_code;
  
  drop database db_shig cascade;